-- AlterTable
ALTER TABLE `reservasi` MODIFY `status_pembayaran` ENUM('PENDING', 'FULL_SENT', 'FULL_REJECTED', 'DP_SENT', 'DP_PAID', 'DP_REJECTED', 'PELUNASAN_SENT', 'PELUNASAN_REJECTED', 'PELUNASAN_PAID', 'PAID', 'REFUNDED') NOT NULL DEFAULT 'PENDING';
